Instructions and Starter Code
lilykriopelle/codecademy-quiz-app pull request #2
Opened 2021-02-25 16:36 UTC by lilykriopelle

2021-02-26 18:39 UTC, ben-spector-cc requested changes

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +* Hint: Inside the `<ul>` returned by the component, replace the empty array with topics stored in state, which you can access by using the selector you wrote in your topics slice. Because the topics
It looks like this logic is already written out for them?

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Next, you'll need to hook the new topic form up to the action creators your slice generates. In **NewTopicForm.js**, import `addTopic` and dispatch it from the event handler that runs when th
I think it would be good to have them import `useDispatch()` here too. What do you think?

2021-02-26 18:39 UTC, ben-spector-cc commented on src/components/NewTopicForm.js
>  import { useDispatch } from "react-redux";
I think it would be useful to have them import useDispatch.

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +* Hint: Use `createSlice` to generate your quizzes slice. Your `addQuiz` action should modify the `quizzes` object in state by adding an object representing a single quiz to the `quizzes` object. Rem
```suggestion
Hint: 
* Use `createSlice` to generate your quizzes slice. 
* Your `addQuiz` action should modify the `quizzes` object in state by adding an object representing a single quiz to the `quizzes` object. 
* Remember, we want the `quizzes` object to be keyed by quiz `id`, so insert your newly created quiz object as the value associated with the `id` you receive in the action's `payload`.
```

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +* Hint: The action creators generated by your slice are accessible through the `actions` property on your slice, and the reducer is accessible via the `reducer` property.
When you implemented the Topics slice, this was included in the same task. I think you can do the same and combine this task with the previous task.

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Next, you should add an action to your topics slice that adds a quiz's `id` to the `quizIds` array of the topic with which the newly quiz is associated. This action action will receive a payl
They will also need to export the new action creator

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Conceptually, these two actions are part of a single process: creating a new quiz and associating it with its topic. Now that you've written both actions, write an action creator that returns
```suggestion
– Task: Conceptually, creating a new quiz and associating it with its topic are part of a single process. Now that you've written both actions, write an action creator that returns a thunk that dispatches them one after the other. This thunk action creator is the one that you will dispatch when a user creates a new quiz.
```

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Conceptually, these two actions are part of a single process: creating a new quiz and associating it with its topic. Now that you've written both actions, write an action creator that returns
I think you should specify that this is written in the quizzesSlice file

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Conceptually, these two actions are part of a single process: creating a new quiz and associating it with its topic. Now that you've written both actions, write an action creator that returns
Also (this might go in the hints) I think you can remind them what the payload structure will be.

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: To test your work, you'll need to connect your action creator to **NewQuizForm** and make that component work. First, import your `topics` selector from your topics slice and replace our vari
```suggestion
– Task: To test your work, you'll need to connect your action creator to **NewQuizForm** and make that component work. First, import your topics selector from your topics slice and replace assign a call to that selector to the variable `topics` (which is currently assigned an empty object).
```

2021-02-26 18:39 UTC, ben-spector-cc commented on src/components/NewQuizForm.js
> -  const topics = useSelector(selectTopics);
Should this be something like:

```js
const topics = {};
```

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Next, import the thunk action creator from your quiz slice and dispatch it from the event handler that fires when the new quiz form is submitted. Remember, that action creator expects to rece
```suggestion
– Task: Next, import the thunk action creator from your quiz slice and dispatch it from the `handleSubmit()` event handler that fires when the new quiz form is submitted. 
* Remember, that action creator expects to receive a payload of the form `{ id: '123', name: 'quiz name', topicId: '456', cardIds: ['1', '2', '3', ...]}`. You'll have to generate an `id` by calling `uuidv4`. For now, pass an empty array for the `cardIds` property (you'll change that in a later task). 
* Test that your action creator works by filling out the new quiz form. After your quiz is created you should be rerouted to the `/quizzes` page and should see your newly created quiz there.
```

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +* Hint: Your event handler should do something like:
```suggestion
* Hint: Your dispatch statement should do something like:
```

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Lastly, import your selector in **Quizzes.js** and **Quiz.js** and make sure those components are displaying the correct data.
```suggestion
– Task: Lastly, import your selector in **Quizzes.js** and **Quiz.js** and make sure those components are displaying the correct data: 
* The **Quizzes** component should render a **Link** for each quiz value in the quizzes slice of state.
* The **Quiz** component uses the `react-router-dom` method `useParams()` to determine the `quizId` to render. Therefore, it needs the full set of quizzes to find the appropriate quiz object to render.
```

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +* Has a `deleteCard` action that will receive a payload containing the `id` of the card to be deleted. Note: the best way to delete a property from an object is to use Javascript's built-in [`delete`
The note about deleting a property from an object should go in the hints.

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +* Hint: Remember, your action creator expects to receive a payload of the form `{ id: '123', front: 'front of card', back: 'back of card'}`. You want to collect all the `cardIds` in an array so that
Include in this hint and example of calling uuidv4()

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +  2. Store the `id` you create for each card in an array.
What do you think about providing the cardIds array as an empty array?

```suggestion
– Task: Lastly, connect your `addCard` action creator to the new quiz form. In **NewQuizForm**, in the event handler that fires when the quiz form is submitted, iterate through the `cards` in that form's local state, and for each one:
  1. Generate an `id` for each card using `uuidv4`.
  2. Store that id in the `cardsId` array.
  3. `dispatch` your `addCard` action creator. 
```

2021-02-26 18:39 UTC, ben-spector-cc commented on src/components/NewQuizForm.js
> -    let cardIds = [];
What do you think about keeping this in?

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: You previously passed an empty array for `cardIds` to the action creator that generates a new quiz. Now that you have  written code to collect an array of all the `cardIds` created whenever t
```suggestion
– Task: You previously passed an empty array for `cardIds` to the action creator that generates a new quiz. Now that you have  written code to collect an array of all the `cardIds` created whenever the new quiz form is submitted, replace the empty array with this array of `cardIds`. 

To test that your code is working, create a new quiz with some cards. Navigate to that quiz from the `/quizzes` page, and verify that your cards show up. Flip them over by clicking on them to make sure that you've correctly captured all of the state belonging to each card.
```

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +– Task: Now that you can add new cards, you'll need to display cards on the individual quiz page. The `Quiz` component renders a list of `Card` components, so in **Card.js**, import your cards select
They also need to import the `useSelector` function

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +* Hint: Remember, that action creator expects to receive a payload of the form `{id: '123'}`. In the event handler that fires whenever a user clicks the trash button, dispatch your action creator wit
Is this in NewQuizForm? If so, you should specify the file.

2021-02-26 18:39 UTC, ben-spector-cc commented on instructions.md
> +Your solution might look different from ours, and that’s okay! There are multiple ways to solve these projects, and you’ll learn more by seeing others’ code.
These are great to have but are used in Portfolio projects, not Challenge projects. You can remove these sections and instead add in a Solutions task group as the third and final task group. Refer to the examples to see how this is done.

2021-02-26 18:39 UTC, ben-spector-cc commented on src/components/NewQuizForm.js
>    const dispatch = useDispatch();
I'd like them to implement importing and using the `useDispatch()` method

2021-02-26 18:39 UTC, ben-spector-cc commented on src/components/NewQuizForm.js
> +import { useDispatch } from "react-redux";
LMK: I think they should do this.

2021-02-26 20:45 UTC, lilykriopelle commented on instructions.md
> +  – Users can delete a card associated with a quiz
Gotcha. Nick asked for me to include descriptions of the interactions available on each page in the project objective in [his feedback here](https://codecademy.atlassian.net/browse/CDEV-626), but I can get rid of it if you think it's overkill.

2021-03-01 18:58 UTC, ben-spector-cc reviewed
Looks good Lily! Thanks for making the changes. Only a few more things to address. Once you resolve them, feel free to begin adding your instructions to Author (without further review) while we wait on the design implementations.

2021-03-01 18:58 UTC, ben-spector-cc commented on instructions.md
> +This project is slightly different than others you have encountered thus far on Codecademy. Instead of a step-by-step tutorial, this project contains a series of open-ended requirements which describ
Nick and I have been discussing removing this first sentence from all of these boilerplate overviews. We'd like to start by removing them from the projects in this skill path.

```suggestion
Instead of a step-by-step tutorial, this project contains a series of open-ended requirements which describe the project you’ll be building. There are many possible ways to correctly fulfill all of these requirements, and you should expect to use the internet, Codecademy, and other resources when you encounter a problem that you cannot easily solve.
```

2021-03-01 18:58 UTC, ben-spector-cc commented on instructions.md
> +  – Users can delete a card associated with a quiz
I definitely think these descriptions should stay in the project but I think there's a better place than the narrative. Maybe this could go below the react-router dependency. Something like:

"At a high level, your application will be able to handle the following URL routes, each with their own functionality:

- On the `'/topics/new'` page:
    - Users can create topics
 - On the `'/topics'` page:
     - Users can view all topics
"

To get the list to render nicely, either make it a bulleted list with sub-bullets, or add line breaks before each "On the X page"

2021-03-01 18:58 UTC, ben-spector-cc commented on instructions.md
> +* Hint: Use `useSelector` conjunction with your selector to access all the topics in state.
```suggestion
* Hint: You will need to import `useSelector` and then call it in conjunction with your selector to access all the topics in state.
```

2021-03-01 18:58 UTC, ben-spector-cc commented on instructions.md
> +* Hint: You will need to include the topic's `name` in the action payload as well as an `id` property (you should generate a value for this property by calling `uuidv4()`).
```suggestion
* Hint: 
- You will need to import and call the `useDispatch()` method in order to dispatch actions to the store.
- You will need to include the topic's `name` in the action payload as well as an `id` property (you should generate a value for this property by calling `uuidv4()`).
```

2021-03-05 14:36 UTC, merged